import { Callout } from 'nextra/components'

---
title: Core. Task Canceled Error
---

[A2A Node SDK - v0.1.0](/api-reference/README) / [Modules](/api-reference/modules) / [Core](/api-reference/modules/Core) / TaskCanceledError

# Class: TaskCanceledError

[Core](/api-reference/modules/Core).TaskCanceledError

Error thrown when attempting to work with a task that was canceled

This error occurs when trying to access or modify a task that has
been canceled by the user or system.

**`Example`**

```typescript
throw new TaskCanceledError('task-123');
```

## Hierarchy

- [`A2AError`](Core.A2AError)

  ↳ **`TaskCanceledError`**

## Table of contents

### Constructors

- [constructor](Core.TaskCanceledError.md#constructor)

### Properties

- [code](Core.TaskCanceledError.md#code)
- [data](Core.TaskCanceledError.md#data)
- [message](Core.TaskCanceledError.md#message)
- [name](Core.TaskCanceledError.md#name)
- [stack](Core.TaskCanceledError.md#stack)
- [stackTraceLimit](Core.TaskCanceledError.md#stacktracelimit)

### Methods

- [captureStackTrace](Core.TaskCanceledError.md#capturestacktrace)
- [prepareStackTrace](Core.TaskCanceledError.md#preparestacktrace)
- [toJSON](Core.TaskCanceledError.md#tojson)

## Constructors

### constructor

• **new TaskCanceledError**(`taskId`): [`TaskCanceledError`](Core.TaskCanceledError)

Creates a new task canceled error

#### Parameters

| Name | Type | Description |
| :------ | :------ | :------ |
| `taskId` | `string` | ID of the canceled task |

#### Returns

[`TaskCanceledError`](Core.TaskCanceledError)

#### Overrides

[A2AError](Core.A2AError).[constructor](Core.A2AError.md#constructor)

## Properties

### code

• `Readonly` **code**: `number`

Numeric error code (typically negative, see ERROR_CODES)

#### Inherited from

[A2AError](Core.A2AError).[code](Core.A2AError.md#code)

___

### data

• `Optional` `Readonly` **data**: `Record`\<`string`, `unknown`\>

Optional additional context data for the error

#### Inherited from

[A2AError](Core.A2AError).[data](Core.A2AError.md#data)

___

### message

• **message**: `string`

#### Inherited from

[A2AError](Core.A2AError).[message](Core.A2AError.md#message)

___

### name

• **name**: `string`

#### Inherited from

[A2AError](Core.A2AError).[name](Core.A2AError.md#name)

___

### stack

• `Optional` **stack**: `string`

#### Inherited from

[A2AError](Core.A2AError).[stack](Core.A2AError.md#stack)

___

### stackTraceLimit

▪ `Static` **stackTraceLimit**: `number`

The `Error.stackTraceLimit` property specifies the number of stack frames
collected by a stack trace (whether generated by `new Error().stack` or
`Error.captureStackTrace(obj)`).

The default value is `10` but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

#### Inherited from

[A2AError](Core.A2AError).[stackTraceLimit](Core.A2AError.md#stacktracelimit)

## Methods

### captureStackTrace

▸ **captureStackTrace**(`targetObject`, `constructorOpt?`): `void`

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

| Name | Type |
| :------ | :------ |
| `targetObject` | `object` |
| `constructorOpt?` | `Function` |

#### Returns

`void`

#### Inherited from

[A2AError](Core.A2AError).[captureStackTrace](Core.A2AError.md#capturestacktrace)

___

### prepareStackTrace

▸ **prepareStackTrace**(`err`, `stackTraces`): `any`

#### Parameters

| Name | Type |
| :------ | :------ |
| `err` | `Error` |
| `stackTraces` | `CallSite`[] |

#### Returns

`any`

**`See`**

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

[A2AError](Core.A2AError).[prepareStackTrace](Core.A2AError.md#preparestacktrace)

___

### toJSON

▸ **toJSON**(): `Object`

Converts the error to a JSON-serializable object

#### Returns

`Object`

JSON representation of the error

| Name | Type |
| :------ | :------ |
| `code` | `number` |
| `data?` | `Record`\<`string`, `unknown`\> |
| `message` | `string` |

#### Inherited from

[A2AError](Core.A2AError).[toJSON](Core.A2AError.md#tojson)
